config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :products
  end
  resources :carts
  resources :products do
    member do
      post :add_to_cart
    end
  end
  namespace :account do
    resources :orders do
      member do
        post :pay
      end
    end
  end
  root "products#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :products, through: :cart_items, as: :products

  def total_price
    sum = 0
    cart_items.each do |cart_item|
      if cart_item.product.price.present?
        sum += cart_item.quantity * cart_item.product.price
      end
    end
    sum
  end
  def clear
    cart_items.destroy_all
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items

  def pay!
    self.update_columns(is_paid: true)
  end

  include AASM
  aasm do
    state :order_placed, :initial => true
    state :is_paid
    state :shipping
    state :shipped
    state :good_returned
    state :order_cancelled
    event :pay_order, :after_commit => :pay! do
      transitions :from => :order_placed, :to => :is_paid
    end
    event :ship do
      transitions :from => :is_paid, :to => :shipping
    end
    event :deliver do
      transitions :from => :shipping, :to => :shipped
    end
    event :cancel_order do
      transitions :from => [:order_placed, :is_paid], :to => :order_canceled
    end
    event :return_good do
      transitions :from => :shipped, :to => :good_returned
    end
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :cart_items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders
end

app/controllers/account/orders_controller.rb
class Account::OrdersController < ApplicationController
  before_action :authenticate_user!
  def new
    @order = Order.new
  end
  def create
    @order = current_user.orders.build(order_params)
    @order.total_price = current_cart.total_price
    if @order.save
      # create oder_items
      current_cart.cart_items.each do |cart_item|
        @order_item = @order.order_items.build
        @order_item.product_name = cart_item.product.title
        @order_item.product_price = cart_item.product.price
        @order_item.quantity = cart_item.quantity
        @order_item.save!
      end
      flash[:notice] = "订单生成成功"
      current_cart.clear
      redirect_to account_order_path(@order)
    else
      render :new
    end
  end
  def show
    @order = Order.find(params[:id])
  end
  def pay
    @order = Order.find(params[:id])
    @order.pay_order!
    flash[:notice] = "付款成功"
    redirect_to :back
  end
  private
  def order_params
    params.require(:order).permit(:customer_name, :phone_number, :address)
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController

  layout "admin"
  def index
    @products = Product.all
  end
  def show
    @product = Product.find(params[:id])
  end
  def new
    @product = Product.new
  end
  def create
    @product= Product.new(product_params)
    if @product.save
      redirect_to admin_products_path
    else
      render :new
    end
  end
  def edit
    @product = Product.find(params[:id])
  end
  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to admin_products_path
    else
      render :edit
    end
  end
  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:warnig] = "Destroy product success"
    redirect_to admin_products_path
  end

  private
  def product_params
    params.require(:product).permit(:title, :description, :quantity, :price, :image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_cart
  def current_cart
    @current_cart ||= Cart.find_by(id: session[:cart_id])
    if @current_cart.blank?
      @current_cart = Cart.create!
    end
    session[:cart_id] = @current_cart.id
    @current_cart
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end
  def show
    @product = Product.find(params[:id])
  end

  def add_to_cart
    @product = Product.find(params[:id])
    @cart_item = current_cart.cart_items.build
    @cart_item.product = @product
    @cart_item.quantity = 1
    @cart_item.save
    flash[:notice] = "已成功加入购物车！"
    redirect_to :back
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    flash[:notice] = "success"
  end
end

app/helpers/account/orders_helper.rb
module Account::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
  def render_total_price(current_cart)
    current_cart.total_price
  end
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice "notice", "alert", "warning", "info"
  end

  FLASH_CLASSES = {notice: "success", alert: "danger", warning: "warning", info: "info"}.freeze
  def flash_class(key)
    FLASH_CLASSES.fetch(key.to_sym, key)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/products/_product_form.html.erb
<%= simple_form_for [:admin, @product] do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :quantity %>
  <%= f.input :price %>
  <% if !@product.image.blank? %>
    <%= image_tag @product.image.url(:medium) %>
  <% else %>
    <%= image_tag "http://placehold.it/200x200?text=No Pic" %>
  <% end %>
  <%= f.input :image %>
  <%= f.submit "Submit", class:"btn btn-primary", data:{disable_with: "Submiting..."} %>

<% end %>

app/views/admin/products/_product_item.html.erb
<tr>
  <td>
    <% if !product.image.blank? %>
      <%= image_tag product.image.url(:thumb) %>
    <% else %>
      <%= image_tag "http://placehold.it/200x200?text=No Pic" %>
    <% end %>
  </td>
  <td><%= product.title %></td>
  <td><%= product.quantity %></td>
  <td><%= product.price %></td>
  <td><%= link_to("edit", edit_admin_product_path(product)) %>
    | <%= link_to("destroy", admin_product_path(product), method: :delete, data: {confirm: "Are you sure?"}) %>
  </td>
</tr>

app/views/admin/products/edit.html.erb
<h2>Edit Product</h2>
<%= render "product_form" %>

app/views/admin/products/index.html.erb
<div class="pull-right" style="margin-bottom: 20px;">
  <%= link_to("New Product", new_admin_product_path, class:"btn btn-primary") %>
</div>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Picture</th>
      <th>title</th>
      <th>quantity</th>
      <th>price</th>
      <th>option</th>
    </tr>
  </thead>
  <tbody>
    <%= render :partial => "product_item", collection: @products, as: :product%>
  </tbody>
</table>

app/views/admin/products/new.html.erb
<h2>New product</h2>
<%= render "product_form" %>

app/views/carts/show.html.erb
<div class="col-md-12">
  <h2>我的购物车</h2>
  <table class="table table-bordered">
    <thead>
      <th >#</th>
      <th>数量</th>
      <th>单价</th>
    </thead>
    <tbody>
      <% current_cart.cart_items.each do |cart_item| %>
        <tr>
          <td>
            <%= link_to product_path(cart_item.product) do %>
              <% if !cart_item.product.image.blank? %>
                <%= image_tag cart_item.product.image.url(:thumb) %>
              <% else %>
                <%= image_tag "http://placehold.it/200x200?text=No Pic" %>
              <% end %>
              <%= cart_item.product.title %></td>
            <% end %>
          <td><%= cart_item.quantity %></td>
          <td><%= cart_item.product.price %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="pull-right">
    <div class="container">
      <p>总计：<%= render_total_price(current_cart) %> CNY</p>
    </div>
    <%= link_to("生成订单", new_account_order_path, class: "btn btn-lg btn-danger") %>
  </div>
</div>

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value|%>
    <div class="alert alert-<%= flash_class(key)%>">
      <%= value %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="text-center" style="margin-top: 100px;">
  Powdered by <b>zedong</b>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">JLU Store</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to("Product", products_path) %></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to(current_cart.cart_items.count, cart_path(current_cart))  %></li>
        <% if current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Hi, <%= current_user.email %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <% if current_user.is_admin %>
                <li><%= link_to("后台",admin_products_path) %></li>
              <% end %>
              <li role="separator" class="divider"></li>
              <li><%= link_to("Log out", destroy_user_session_path, method: :delete) %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to("Sign up", new_user_registration_path) %></li>
          <li><%= link_to("Log in", new_user_session_path) %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JLU Store</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render "common/navbar" %>
      <%= render "common/flashes" %>
      <div class="row">
        <div class="col-md-2">
          <ul class="nav nav-pills nav-stacked">
            <li role="presentation" class="active"><%= link_to("Admin", "#") %></li>
            <li role="presentation"><%= link_to("Product", admin_products_path) %></li>
            <li role="presentation"><a href="#">Messages</a></li>
          </ul>
        </div>
        <div class="col-md-10">
          <%= yield %>
        </div>
      </div>
    </div>
    <%= render "common/footer" %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JLU Store</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render "common/navbar" %>
      <%= render "common/flashes" %>
      <%= yield %>
    </div>
    <%= render "common/footer" %>
  </body>
</html>

app/views/products/_product_item.html.erb
<div class="col-md-2">
  <div class="thumbnail">
    <%= link_to product_path(product) do %>
      <% if !product.image.blank? %>
        <%= image_tag product.image.url(:thumb) %>
      <% else %>
        <%= image_tag "http://placehold.it/200x200?text=No Pic" %>
      <% end %>
      <div class="caption text-center">
        <h4><%= product.title %> - ¥ <%= product.price %></h4>
      </div>
    <% end %>
  </div>
</div>

app/views/products/index.html.erb
<div class="row">
  <%= render :partial => "product_item", collection: @products, as: :product%>
</div>

app/views/products/show.html.erb
<div class="row">
  <div class="col-md-6">
    <% if !@product.image.blank? %>
      <%= image_tag @product.image.url(:medium) %>
    <% else %>
      <%= image_tag "http://placehold.it/200x200?text=No Pic" %>
    <% end %>
  </div>
  <div class="col-md-6">
    <div class="container">
      <h2><%= @product.title %></h2>
      <p><%= @product.description %></p>
    </div>
    <hr>
    <div style="margin: 30px;">
      <p>¥ <%= @product.price %></p>
      <p>库存：<%= @product.quantity %></p>
    </div>
    <div class="pull-right">
      <%= link_to("加入购物车", add_to_cart_product_path(@product),method: :post, class: "btn btn-lg btn-danger") %>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<h2>Hello world</h2>